### PR TITLE
Change the way the relic works

### PR DESCRIPTION
**Pull request by luke-shepherd-light**
Loss of relic will make dogma bonuses harder to earn

### CODE REVIEW

**Comment by luke-shepherd-light** [comment]
This change will increase the cost for new dogma bonuses if the the relic is lost but will allow existing dogma bonuses to operate as normal.

**Comment by eightyeightbrands** [comment]
Did you test this?

**Comment by KingKolSWE** [comment]
Does this apply any further increased cost?  Since a faith can have all their Dogmas and this does nothing if the relic is lost, but allow them to continue using their dogmas?

**Comment by luke-shepherd-light** [comment]
No, this has not been tested. If would allow the religion to keep their existing dogma bonuses at not extra cost, but would be expensive to change a dogma without using the relic.

**Pull request closed without merging**
